# Generated by Django 5.2.8 on 2025-12-02 15:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('level', models.CharField(choices=[('HSK1', 'HSK 1 (Начальный)'), ('HSK2', 'HSK 2'), ('HSK3', 'HSK 3 (Средний)'), ('HSK4', 'HSK 4'), ('HSK5', 'HSK 5 (Продвинутый)'), ('HSK6', 'HSK 6')], max_length=10, verbose_name='Уровень HSK')),
                ('days_description', models.CharField(max_length=100, verbose_name='Расписание')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата старта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Группа активна')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя / Никнейм')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('telegram_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram Username')),
                ('status', models.CharField(choices=[('new', '🔥 Новый'), ('process', '⏳ В обработке'), ('payment', '💰 Ждем оплату'), ('won', '✅ Записан в группу'), ('lost', '❌ Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Лид (Заявка)',
                'verbose_name_plural': 'Лиды (Заявки)',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('lessons_count', models.IntegerField(verbose_name='Количество уроков')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО Преподавателя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает сейчас')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('is_from_manager', models.BooleanField(default=False, verbose_name='От менеджера?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.lead')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата урока')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Тема урока')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Проведенный урок',
                'verbose_name_plural': 'Журнал уроков',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('student_status', models.CharField(choices=[('active', '🟢 Активен'), ('paused', '🟡 Заморозка'), ('banned', '🔴 Исключен (Много прогулов)')], default='active', max_length=20, verbose_name='Статус студента')),
                ('balance', models.IntegerField(default=0, verbose_name='Остаток уроков')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего денег принес')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.group', verbose_name='Группа')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lead', verbose_name='Из какого лида')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student', verbose_name='Студент')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tariff', verbose_name='Купленный тариф')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'История оплат',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Что сделать?')),
                ('description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок')),
                ('priority', models.CharField(choices=[('low', '🟢 Низкий'), ('medium', '🟡 Средний'), ('high', '🔴 Высокий (Срочно!)')], default='medium', max_length=10, verbose_name='Важность')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', '✅ Выполнено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи сотрудникам',
                'ordering': ['status', '-priority'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', '✅ Присутствовал (-1 урок)'), ('absent', '❌ Прогул (-1 урок)'), ('excused', '🏥 Уважительная причина (0 уроков)')], default='present', max_length=20, verbose_name='Статус')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
