# Generated by Django 5.2.8 on 2025-12-01 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Группа HSK-1 Вечер', max_length=100, verbose_name='Название группы')),
                ('level', models.CharField(choices=[('HSK1', 'HSK 1 (Начальный)'), ('HSK2', 'HSK 2'), ('HSK3', 'HSK 3 (Средний)'), ('HSK4', 'HSK 4'), ('HSK5', 'HSK 5 (Продвинутый)'), ('HSK6', 'HSK 6')], max_length=10, verbose_name='Уровень HSK')),
                ('days_description', models.CharField(help_text='Например: Пн/Ср 19:00', max_length=100, verbose_name='Расписание')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата старта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Группа активна')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', '🔥 Новый'), ('process', '⏳ В обработке'), ('payment', '💰 Ждем оплату'), ('won', '✅ Записан в группу'), ('lost', '❌ Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник (откуда узнал)')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Лид (Заявка)',
                'verbose_name_plural': 'Лиды (Заявки)',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО Преподавателя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает сейчас')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('balance', models.IntegerField(default=0, verbose_name='Остаток уроков')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего денег принес')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.group', verbose_name='Группа')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lead', verbose_name='Из какого лида')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='Преподаватель'),
        ),
    ]
