# Generated by Django 5.2.8 on 2025-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('voice', 'Голосовое'), ('document', 'Файл')], default='text', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст/Подпись'),
        ),
    ]
