# Generated by Django 5.2.8 on 2025-12-01 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('active', '🟢 Активен'), ('paused', '🟡 Заморозка'), ('banned', '🔴 Исключен (Много прогулов)')], default='active', max_length=20, verbose_name='Статус студента'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата урока')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Тема урока')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Проведенный урок',
                'verbose_name_plural': 'Журнал уроков',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', '✅ Присутствовал (-1 урок)'), ('absent', '❌ Прогул (-1 урок)'), ('excused', '🏥 Уважительная причина (0 уроков)')], default='present', max_length=20, verbose_name='Статус')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.lesson')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
