# Generated by Django 5.2.8 on 2025-12-01 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_student_status_lesson_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Абонемент 8 занятий', max_length=100, verbose_name='Название тарифа')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('lessons_count', models.IntegerField(verbose_name='Количество уроков')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Может отличаться от цены тарифа, если была скидка', max_digits=10, verbose_name='Сумма оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student', verbose_name='Студент')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tariff', verbose_name='Купленный тариф')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'История оплат',
                'ordering': ['-date'],
            },
        ),
    ]
