# Generated by Django 5.2.8 on 2025-12-01 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tariff_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Что сделать?')),
                ('description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок')),
                ('priority', models.CharField(choices=[('low', '🟢 Низкий'), ('medium', '🟡 Средний'), ('high', '🔴 Высокий (Срочно!)')], default='medium', max_length=10, verbose_name='Важность')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', '✅ Выполнено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи сотрудникам',
                'ordering': ['status', '-priority'],
            },
        ),
    ]
