"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b9cr#5pyo&h!4+6)j_%c^kw=r20iwn!^7gv^x4sap)k!d6)_s('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LANGUAGE_CODE = 'ru-ru'
# Подключаем функцию перевода
from django.utils.translation import gettext_lazy as _

# Какие языки будут в меню
LANGUAGES = [
    ('ru', 'Русский'),
    ('en', 'English'),
    ('zh-hans', 'Chinese'), # Китайский упрощенный
    ('uz', 'Uzbek'),        # Узбекский
]

# Включаем систему перевода
USE_I18N = True
USE_L10N = True
TIME_ZONE = 'Asia/Tashkent' 

JAZZMIN_SETTINGS = {
    
    "site_title": "China CRM",
    "site_header": "China Center",
    "site_brand": "Система Управления",
    "welcome_sign": "Привет! Работаем.",
    "copyright": "China Center",
    "search_model": "core.Student",

    # МЕНЮ
    "topmenu_links": [
        {"name": "Открыть сайт", "url": "/", "new_window": True},
    ],
    "order_with_respect_to": ["core.Lead", "core.Student", "core.Group", "core.Teacher"],

    # ИКОНКИ
    "icons": {
        "auth": "fas fa-users-cog",
        "core.Lead": "fas fa-fire",             
        "core.Student": "fas fa-user-graduate", 
        "core.Teacher": "fas fa-chalkboard-teacher", 
        "core.Group": "fas fa-users",           
        # Добавим иконку для новых Задач, раз уж мы здесь
        "core.Task": "fas fa-tasks",
    },
    "default_icon_parents": "fas fa-circle",
    "default_icon_children": "fas fa-dot-circle",
    
    "hide_apps": ["auth"], 
    
    # --- ВОТ ЭТА НОВАЯ СТРОЧКА ---
    "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",  # <--- ТЕМНАЯ ТЕМА (Попробуй также "cyborg" или "slate", если эта не зайдет)
    # "theme": "flatly", # (Раскомментируй эту строку и закомментируй верхнюю, если захочешь вернуть светлую)
    
    "dark_mode_theme": "darkly",
    
    # Настройки меню
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "accent": "accent-primary",
    
    # Кнопки
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

STATIC_ROOT = BASE_DIR / 'staticfiles'